### PR TITLE
Cosmetics - fixing broken links.

### PR DESCRIPTION
**Pull request by rjbordon**
Just some cosmetics fixes to properly set some links to samples!

Thank you for these patterns BTW!

### CODE REVIEW

**Comment by rjbordon** [comment]
@googlebot I signed it!

**Comment by rjbordon** [comment]
cc @rezarokni

**Comment by dsdinter** [comment]
LGTM - Thanks for the contribution @rjbordon !

**Comment by rjbordon** [comment]
Thank you guys! Awesome work!

**Pull request merged**
